
import React, { useState, useEffect, useRef } from 'react';
import { ArrowLeft, Check, HelpCircle, List, X, ChevronLeft, ChevronRight, Clock, AlertTriangle } from 'lucide-react';
import { TacticalButton } from '../../ui/TacticalButton';
import { motion, AnimatePresence } from 'framer-motion';

interface CrosswordGameProps {
  onBack: () => void;
}

interface Clue {
  id: number;
  number: number;
  direction: 'across' | 'down';
  text: string;
  answer: string;
  row: number;
  col: number;
}

// Puzzle Configuration: Hitting Mechanics
const CLUES: Clue[] = [
  { id: 1, number: 1, direction: 'across', text: 'Initial setup in the box', answer: 'STANCE', row: 0, col: 0 },
  { id: 2, number: 2, direction: 'down', text: 'When you swing relative to the pitch', answer: 'TIMING', row: 0, col: 1 },
  { id: 3, number: 3, direction: 'down', text: 'Weight transfer back before the stride', answer: 'LOAD', row: 0, col: 2 },
  { id: 4, number: 4, direction: 'across', text: 'The space between outfielders', answer: 'GAP', row: 5, col: 1 },
  { id: 5, number: 5, direction: 'down', text: 'Generated by hip rotation and bat speed', answer: 'POWER', row: 5, col: 3 },
];

const GRID_SIZE = 10;

export const CrosswordGame: React.FC<CrosswordGameProps> = ({ onBack }) => {
  // State
  const [grid, setGrid] = useState<string[][]>(Array(GRID_SIZE).fill('').map(() => Array(GRID_SIZE).fill('')));
  const [userGrid, setUserGrid] = useState<string[][]>(Array(GRID_SIZE).fill('').map(() => Array(GRID_SIZE).fill('')));
  const [selectedCell, setSelectedCell] = useState<{r: number, c: number} | null>(null);
  const [currentDirection, setCurrentDirection] = useState<'across' | 'down'>('across');
  
  // Game State
  const [gameState, setGameState] = useState<'playing' | 'won' | 'submitted'>('playing');
  const [showClues, setShowClues] = useState(false);
  
  // Timer State
  const [elapsedTime, setElapsedTime] = useState(0);
  const [scoreStats, setScoreStats] = useState({ correct: 0, total: 0, percentage: 0 });

  // Refs for inputs to manage focus
  const inputRefs = useRef<(HTMLInputElement | null)[][]>([]);

  // Initialize Input Refs Array
  if (inputRefs.current.length !== GRID_SIZE) {
    inputRefs.current = Array(GRID_SIZE).fill(null).map(() => Array(GRID_SIZE).fill(null));
  }

  // Build the answer grid on mount
  useEffect(() => {
    const newGrid = Array(GRID_SIZE).fill('').map(() => Array(GRID_SIZE).fill(''));
    CLUES.forEach(clue => {
      const chars = clue.answer.split('');
      chars.forEach((char, idx) => {
        if (clue.direction === 'across') {
          newGrid[clue.row][clue.col + idx] = char;
        } else {
          newGrid[clue.row + idx][clue.col] = char;
        }
      });
    });
    setGrid(newGrid);
  }, []);

  // Timer Effect
  useEffect(() => {
    let interval: any;
    if (gameState === 'playing') {
      interval = setInterval(() => {
        setElapsedTime(prev => prev + 1);
      }, 1000);
    }
    return () => clearInterval(interval);
  }, [gameState]);

  // Auto-Check for Perfect Win condition
  useEffect(() => {
    if (gameState !== 'playing') return;

    const isFilled = userGrid.some(row => row.some(cell => cell !== ''));
    if (!isFilled) return;

    let isCorrect = true;
    let hasEmpty = false;

    let totalLetters = 0;
    let correctLetters = 0;

    for(let r=0; r<GRID_SIZE; r++) {
        for(let c=0; c<GRID_SIZE; c++) {
            if (grid[r][c] !== '') {
                totalLetters++;
                if (userGrid[r][c] === '') hasEmpty = true;
                if (userGrid[r][c] === grid[r][c]) correctLetters++;
                else isCorrect = false;
            }
        }
    }

    if (isCorrect && !hasEmpty) {
        setScoreStats({ correct: totalLetters, total: totalLetters, percentage: 100 });
        setGameState('won');
    }
  }, [userGrid, grid, gameState]);

  const formatTime = (seconds: number) => {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m}:${s.toString().padStart(2, '0')}`;
  };

  const handleManualSubmit = () => {
      let totalLetters = 0;
      let correctLetters = 0;

      for(let r=0; r<GRID_SIZE; r++) {
          for(let c=0; c<GRID_SIZE; c++) {
              if (grid[r][c] !== '') {
                  totalLetters++;
                  if (userGrid[r][c] === grid[r][c]) correctLetters++;
              }
          }
      }

      const percentage = Math.round((correctLetters / totalLetters) * 100);
      setScoreStats({ correct: correctLetters, total: totalLetters, percentage });
      
      if (percentage === 100) {
          setGameState('won');
      } else {
          setGameState('submitted');
      }
      setSelectedCell(null);
  };

  const handleCellClick = (r: number, c: number) => {
    if (grid[r][c] === '' || gameState !== 'playing') return;

    if (selectedCell?.r === r && selectedCell?.c === c) {
        setCurrentDirection(currentDirection === 'across' ? 'down' : 'across');
    } else {
        setSelectedCell({ r, c });
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent, r: number, c: number) => {
    if (!selectedCell || gameState !== 'playing') return;

    // Navigation
    if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(e.key)) {
        e.preventDefault();
        let nr = r, nc = c;
        if (e.key === 'ArrowUp') nr--;
        if (e.key === 'ArrowDown') nr++;
        if (e.key === 'ArrowLeft') nc--;
        if (e.key === 'ArrowRight') nc++;

        // Skip empty cells
        while(nr >= 0 && nr < GRID_SIZE && nc >= 0 && nc < GRID_SIZE && grid[nr][nc] === '') {
             if (e.key === 'ArrowUp') nr--;
             if (e.key === 'ArrowDown') nr++;
             if (e.key === 'ArrowLeft') nc--;
             if (e.key === 'ArrowRight') nc++;
        }

        if (nr >= 0 && nr < GRID_SIZE && nc >= 0 && nc < GRID_SIZE && grid[nr][nc] !== '') {
            setSelectedCell({ r: nr, c: nc });
            inputRefs.current[nr][nc]?.focus();
        }
        return;
    }

    // Backspace
    if (e.key === 'Backspace') {
        e.preventDefault();
        const newGrid = [...userGrid];
        newGrid[r][c] = '';
        setUserGrid(newGrid);

        // Move back logic
        if (currentDirection === 'across') {
            let nc = c - 1;
            while (nc >= 0 && grid[r][nc] === '') nc--;
            if (nc >= 0) {
                setSelectedCell({ r, c: nc });
                inputRefs.current[r][nc]?.focus();
            }
        } else {
            let nr = r - 1;
            while (nr >= 0 && grid[nr][c] === '') nr--;
            if (nr >= 0) {
                setSelectedCell({ r: nr, c });
                inputRefs.current[nr][c]?.focus();
            }
        }
        return;
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>, r: number, c: number) => {
    if (gameState !== 'playing') return;
    const val = e.target.value.toUpperCase();
    if (!/^[A-Z]?$/.test(val)) return;

    const newGrid = [...userGrid];
    newGrid[r][c] = val;
    setUserGrid(newGrid);

    if (val !== '') {
        // Auto-advance
        if (currentDirection === 'across') {
            let nc = c + 1;
            while (nc < GRID_SIZE && grid[r][nc] === '') nc++;
            if (nc < GRID_SIZE) {
                setSelectedCell({ r, c: nc });
                inputRefs.current[r][nc]?.focus();
            }
        } else {
            let nr = r + 1;
            while (nr < GRID_SIZE && grid[nr][c] === '') nr++;
            if (nr < GRID_SIZE) {
                setSelectedCell({ r: nr, c });
                inputRefs.current[nr][c]?.focus();
            }
        }
    }
  };

  // Helper to find the active clue
  const getActiveClue = () => {
    if (!selectedCell) return null;
    return CLUES.find(clue => {
      if (clue.direction !== currentDirection) return false;
      if (clue.direction === 'across') {
        return clue.row === selectedCell.r && selectedCell.c >= clue.col && selectedCell.c < clue.col + clue.answer.length;
      } else {
        return clue.col === selectedCell.c && selectedCell.r >= clue.row && selectedCell.r < clue.row + clue.answer.length;
      }
    });
  };

  const activeClue = getActiveClue();

  // Determine if a cell is part of the active word (for secondary highlighting)
  const isCellInActiveWord = (r: number, c: number) => {
      if (!activeClue) return false;
      if (activeClue.direction === 'across') {
          return activeClue.row === r && c >= activeClue.col && c < activeClue.col + activeClue.answer.length;
      } else {
          return activeClue.col === c && r >= activeClue.row && r < activeClue.row + activeClue.answer.length;
      }
  };

  const handleNavClue = (direction: 'prev' | 'next') => {
      // Flatten clues into a consistent order for traversal
      const allClues = [...CLUES].sort((a, b) => a.number - b.number || (a.direction === 'across' ? -1 : 1));
      
      let nextIdx = 0;
      if (activeClue) {
          const currentIdx = allClues.findIndex(c => c.id === activeClue.id);
          if (direction === 'next') {
              nextIdx = (currentIdx + 1) % allClues.length;
          } else {
              nextIdx = (currentIdx - 1 + allClues.length) % allClues.length;
          }
      } else {
          nextIdx = 0;
      }
      
      const targetClue = allClues[nextIdx];
      setSelectedCell({ r: targetClue.row, c: targetClue.col });
      setCurrentDirection(targetClue.direction);
      inputRefs.current[targetClue.row][targetClue.col]?.focus();
  };

  const activateClueFromList = (clue: Clue) => {
      setSelectedCell({ r: clue.row, c: clue.col });
      setCurrentDirection(clue.direction);
      inputRefs.current[clue.row][clue.col]?.focus();
      setShowClues(false);
  }

  return (
    <div className="max-w-4xl mx-auto relative flex flex-col h-[calc(100vh-8rem)]">
      
      {/* Unified Header & Clue Display */}
      <header className="flex items-center justify-between mb-6 bg-white border-2 border-duo-gray-200 rounded-2xl p-2 shadow-sm shrink-0 min-h-[4.5rem] relative z-20">
        <div className="flex items-center gap-2 shrink-0">
            <button onClick={onBack} className="p-3 hover:bg-duo-gray-100 rounded-xl text-duo-gray-500 transition-colors">
                <ArrowLeft size={24} />
            </button>
        </div>

        <div className="flex-1 px-2 text-center flex items-center justify-center overflow-hidden">
            <AnimatePresence mode='wait'>
                {activeClue ? (
                    <motion.div 
                        key="clue-view"
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -10 }}
                        className="flex items-center justify-between w-full max-w-xl"
                    >
                         <button onClick={() => handleNavClue('prev')} className="p-2 hover:bg-duo-gray-100 rounded-full text-duo-gray-400 transition-colors shrink-0">
                            <ChevronLeft size={24} />
                        </button>
                        
                        <div className="flex-1 px-2 flex flex-col items-center">
                            <div className="flex items-center gap-2 mb-0.5">
                                <div className="text-[10px] font-extrabold text-duo-blue uppercase bg-duo-blue/10 px-2 py-0.5 rounded">
                                    {activeClue.number} {activeClue.direction}
                                </div>
                                <div className="text-xs font-mono font-extrabold text-duo-gray-400 bg-duo-gray-100 px-2 py-0.5 rounded flex items-center gap-1">
                                    <Clock size={10} /> {formatTime(elapsedTime)}
                                </div>
                            </div>
                            <div className="font-extrabold text-duo-gray-800 text-sm leading-tight line-clamp-2">
                                {activeClue.text}
                            </div>
                        </div>

                        <button onClick={() => handleNavClue('next')} className="p-2 hover:bg-duo-gray-100 rounded-full text-duo-gray-400 transition-colors shrink-0">
                            <ChevronRight size={24} />
                        </button>
                    </motion.div>
                ) : (
                    <motion.div 
                        key="title-view"
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -10 }}
                        className="flex flex-col items-center"
                    >
                        <h1 className="text-lg sm:text-xl font-extrabold text-duo-gray-800 leading-none">Tactical Crossword</h1>
                        <div className="flex items-center gap-2 mt-1">
                            <span className="text-[10px] font-extrabold text-duo-gray-400 uppercase">Module 1</span>
                            <div className="text-xs font-mono font-extrabold text-duo-gray-500 bg-duo-gray-100 px-2 py-0.5 rounded flex items-center gap-1">
                                <Clock size={12} /> {formatTime(elapsedTime)}
                            </div>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>

        <div className="flex items-center gap-2 shrink-0">
             <button 
                onClick={handleManualSubmit}
                disabled={gameState !== 'playing'}
                className="bg-duo-blue text-white p-2 sm:px-4 sm:py-2 rounded-xl font-extrabold text-xs sm:text-sm hover:bg-duo-blueDark disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 shadow-sm"
             >
                <Check size={18} />
                <span className="hidden sm:inline">SUBMIT</span>
             </button>
             <button 
                onClick={() => setShowClues(true)} 
                className="p-2 sm:px-3 sm:py-2 bg-duo-gray-100 text-duo-gray-500 hover:bg-duo-gray-200 rounded-xl font-extrabold text-xs sm:text-sm flex items-center gap-2"
             >
                 <List size={18} />
             </button>
        </div>
      </header>

      {/* Clues Overlay Modal */}
      <AnimatePresence>
        {showClues && (
           <motion.div 
             initial={{ opacity: 0, scale: 0.95 }}
             animate={{ opacity: 1, scale: 1 }}
             exit={{ opacity: 0, scale: 0.95 }}
             className="absolute inset-0 z-50 bg-white rounded-3xl shadow-2xl flex flex-col overflow-hidden border-2 border-duo-gray-200"
           >
              <div className="p-4 border-b-2 border-duo-gray-100 flex justify-between items-center bg-duo-gray-50">
                  <h3 className="font-extrabold text-duo-gray-800 flex items-center gap-2 text-lg">
                      <HelpCircle size={24} className="text-duo-blue" /> Mission Intel
                  </h3>
                  <button onClick={() => setShowClues(false)} className="p-2 hover:bg-duo-gray-200 rounded-full transition-colors text-duo-gray-500">
                      <X size={24} />
                  </button>
              </div>
              
              <div className="flex-1 overflow-y-auto p-6 custom-scrollbar">
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <div>
                        <h4 className="flex items-center gap-2 text-xs font-extrabold text-white bg-duo-gray-400 px-3 py-1 rounded-lg uppercase mb-4 w-fit">
                            Across <span className="opacity-60">→</span>
                        </h4>
                        <div className="space-y-2">
                            {CLUES.filter(c => c.direction === 'across').map(clue => (
                                <div 
                                    key={clue.id}
                                    onClick={() => activateClueFromList(clue)}
                                    className={`flex gap-3 p-3 rounded-xl cursor-pointer transition-all border-l-4 hover:bg-duo-gray-50 ${
                                        activeClue?.id === clue.id ? 'bg-duo-blue/5 border-duo-blue' : 'border-transparent'
                                    }`}
                                >
                                    <span className="font-extrabold text-duo-blue">{clue.number}</span>
                                    <span className="font-bold text-duo-gray-700 text-sm">{clue.text}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                    
                    <div>
                        <h4 className="flex items-center gap-2 text-xs font-extrabold text-white bg-duo-gray-400 px-3 py-1 rounded-lg uppercase mb-4 w-fit">
                            Down <span className="opacity-60">↓</span>
                        </h4>
                        <div className="space-y-2">
                            {CLUES.filter(c => c.direction === 'down').map(clue => (
                                <div 
                                    key={clue.id}
                                    onClick={() => activateClueFromList(clue)}
                                    className={`flex gap-3 p-3 rounded-xl cursor-pointer transition-all border-l-4 hover:bg-duo-gray-50 ${
                                        activeClue?.id === clue.id ? 'bg-duo-blue/5 border-duo-blue' : 'border-transparent'
                                    }`}
                                >
                                    <span className="font-extrabold text-duo-blue">{clue.number}</span>
                                    <span className="font-bold text-duo-gray-700 text-sm">{clue.text}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                 </div>
              </div>
           </motion.div>
        )}
      </AnimatePresence>

      {/* Game Board Area */}
      <div className="flex-1 flex flex-col items-center relative justify-center">
            <AnimatePresence>
                {gameState !== 'playing' && (
                    <motion.div 
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        exit={{ opacity: 0, scale: 0.9 }}
                        className="absolute inset-0 z-40 flex items-center justify-center bg-white/80 backdrop-blur-sm rounded-3xl"
                    >
                        <div className={`text-white p-8 rounded-3xl flex flex-col items-center text-center shadow-2xl max-w-md mx-4 border-4 border-white ${gameState === 'won' ? 'bg-gradient-to-b from-duo-green to-green-600' : 'bg-gradient-to-b from-duo-blue to-duo-blueDark'}`}>
                            <div className="w-20 h-20 bg-white/20 backdrop-blur rounded-full flex items-center justify-center text-white mb-4 border-4 border-white/30 shadow-inner">
                                {gameState === 'won' ? <Check size={48} strokeWidth={4} /> : <AlertTriangle size={48} strokeWidth={3} />}
                            </div>
                            
                            <h3 className="text-3xl font-extrabold uppercase italic tracking-wide mb-2">
                                {gameState === 'won' ? 'Mission Complete' : 'Debriefing Report'}
                            </h3>
                            
                            <div className="grid grid-cols-2 gap-4 w-full my-6 bg-black/10 rounded-2xl p-4">
                                <div>
                                    <div className="text-xs font-bold text-white/70 uppercase">Accuracy</div>
                                    <div className="text-2xl font-extrabold">{scoreStats.percentage}%</div>
                                </div>
                                <div>
                                    <div className="text-xs font-bold text-white/70 uppercase">Time</div>
                                    <div className="text-2xl font-extrabold">{formatTime(elapsedTime)}</div>
                                </div>
                            </div>

                            <p className="text-white/90 font-medium text-lg mb-6">
                                {gameState === 'won' 
                                    ? "Sector secured. Knowledge base updated. +50 XP Awarded." 
                                    : `Incomplete data detected. You correctly identified ${scoreStats.correct} out of ${scoreStats.total} targets.`
                                }
                            </p>
                            
                            <div className="flex gap-4 w-full">
                                <button 
                                    onClick={() => {
                                        setUserGrid(Array(GRID_SIZE).fill('').map(() => Array(GRID_SIZE).fill('')));
                                        setGameState('playing');
                                        setSelectedCell(null);
                                        setElapsedTime(0);
                                        setScoreStats({ correct: 0, total: 0, percentage: 0 });
                                    }}
                                    className={`flex-1 py-3 font-extrabold rounded-xl shadow-md transition-colors ${gameState === 'won' ? 'bg-white text-duo-green hover:bg-gray-50' : 'bg-white text-duo-blue hover:bg-gray-50'}`}
                                >
                                    Replay
                                </button>
                                <button 
                                    onClick={onBack}
                                    className={`flex-1 py-3 font-extrabold rounded-xl shadow-md transition-colors ${gameState === 'won' ? 'bg-duo-greenDark text-white hover:bg-green-800' : 'bg-duo-gray-800 text-white hover:bg-gray-900'}`}
                                >
                                    Exit
                                </button>
                            </div>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>

            <div className="bg-duo-gray-800 rounded-[2rem] shadow-2xl overflow-hidden border-4 border-duo-gray-800 relative z-0 max-w-full max-h-full">
                <div className="absolute inset-0 opacity-10 pointer-events-none bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')]"></div>

                <div className="p-4 sm:p-8 flex justify-center overflow-auto max-h-full custom-scrollbar">
                    <div 
                        className="grid gap-[2px] bg-duo-gray-800 border-[2px] border-duo-gray-800"
                        style={{ 
                            gridTemplateColumns: `repeat(${GRID_SIZE}, minmax(0, 1fr))`,
                            width: 'fit-content'
                        }}
                    >
                        {grid.map((row, r) => (
                            row.map((cell, c) => {
                                const isPlayable = cell !== '';
                                const isSelected = selectedCell?.r === r && selectedCell?.c === c;
                                const isInActiveWord = isCellInActiveWord(r, c);
                                const clueNum = CLUES.find(clue => clue.row === r && clue.col === c)?.number;

                                // Logic for displaying answers after submit
                                const displayValue = (gameState === 'playing') ? userGrid[r][c] : grid[r][c];
                                const isCorrect = userGrid[r][c] === grid[r][c];
                                const wasWrong = (gameState === 'submitted') && !isCorrect;

                                return (
                                    <div key={`${r}-${c}`} className="relative w-8 h-8 sm:w-10 sm:h-10 md:w-11 md:h-11">
                                        {isPlayable ? (
                                            <div className="w-full h-full relative">
                                                <input
                                                    ref={(el) => { inputRefs.current[r][c] = el; }}
                                                    type="text"
                                                    maxLength={1}
                                                    value={displayValue}
                                                    onChange={(e) => handleChange(e, r, c)}
                                                    onKeyDown={(e) => handleKeyDown(e, r, c)}
                                                    onClick={() => handleCellClick(r, c)}
                                                    readOnly={gameState !== 'playing'}
                                                    className={`
                                                        w-full h-full text-center text-base sm:text-lg md:text-xl font-extrabold uppercase caret-transparent focus:outline-none transition-colors duration-150 rounded-sm
                                                        ${isSelected ? 'bg-duo-blue text-white z-10 relative shadow-md transform scale-105' : 
                                                          wasWrong ? 'bg-duo-red/10 text-duo-red' :
                                                          isInActiveWord ? 'bg-duo-blue/20 text-duo-gray-800' : 'bg-white text-duo-gray-800 hover:bg-duo-gray-50'}
                                                        ${gameState !== 'playing' ? 'cursor-default' : ''}
                                                    `}
                                                />
                                                {clueNum && (
                                                    <span className={`absolute top-0.5 left-0.5 text-[8px] sm:text-[9px] font-extrabold leading-none pointer-events-none z-20 ${isSelected ? 'text-white/90' : 'text-duo-gray-400'}`}>
                                                        {clueNum}
                                                    </span>
                                                )}
                                            </div>
                                        ) : (
                                            <div className="w-full h-full bg-duo-gray-800/50">
                                                <div className="w-full h-full opacity-20 bg-[radial-gradient(circle,_#4b5563_1px,_transparent_1px)] bg-[size:4px_4px]"></div>
                                            </div>
                                        )}
                                    </div>
                                );
                            })
                        ))}
                    </div>
                </div>
            </div>
      </div>
    </div>
  );
};
